### ISSUE TITLE
just one gpu (of 2) detected and mining

### ISSUE THREAD

**Issue by radioice104** [glph3k/cast_xmr#10]
When using Cast XMR Vega 1.7.1 just the first card (0) is detected and mining ok.
The second one is not detected.
I have tried -g 0,1 etc
Tried without -g
Not working

[12:04:45] Initializing GPU, loading kernel ...
Detected OpenCL Platform: OpenCL 2.0 AMD-APP (2442.12)
Blockchain Compute Driver detected.
GPU0: Radeon RX 580 Series (Ellesmere) | 36 Compute Units | Memory (MB): 8192 | Intensity: 7 / 10
[12:04:46] Connecting to bittube.miner.rocks:7777 ...
[12:04:46] Connected to pool.

The one is not working(detected) is a vega 64 card
cast_xmr-vega --algo=-5 -S bittube.miner.rocks:7777 -u xxx -g 0,1
Any ideas?

**Comment by glph3k** [comment]
Please use the option -G 0,1 to specify first and second GPU. Make sure the "g" is uppercase.
