### ISSUE TITLE
Update for SUMO's Algorithm Change

### ISSUE THREAD

**Issue by ProfDD** [glph3k/cast_xmr#2]
Hi glph3k, Could you contact the team of **Sumokoin** for their upcoming update? SUMO will have algorithm changing issue but it's not same as Monero's V7, and that require mining software to be updated too. 

Otherwise, RX Vega might not able to mine SUMO after the update in April.

Thanks

**Comment by glph3k** [comment]
Implemented in Cast XMR version 0.9.6
