### ISSUE TITLE
Update Algo for Haven V3 Hardfork

### ISSUE THREAD

**Issue by havenprotocol** [glph3k/cast_xmr#4]
Hi there,

We are switching to a modified CryptoNight Heavy algo (CryptoNight Haven) in our next hardfork due next week. It would be great to have a compiled Cast XMR ready for the release as we have a huge amount of miners that use Cast.

The tweak is very small you can find the details here:
https://github.com/havenprotocol/haven/commit/be8648c318ad7622960e01f674208181219b5c63

This was my PR to xmr-stak with the changes:
https://github.com/fireice-uk/xmr-stak/pull/1639/files

Thank you!

**Comment by glph3k** [comment]
Ok, at it. Is there a test pool available?

**Comment by glph3k** [comment]
Haven XHV V3 support added in Cast XMR 1.2.0
