### ISSUE TITLE
Wrong year on website Ubuntu download page

### ISSUE THREAD

**Issue by JoshLambda** [glph3k/cast_xmr#9]
On website Ubuntu download page, it says:
Updated on January 26th, 201**8** to version 1.7.1

instead of:
Updated on January 26th, 201**9** to version 1.7.1

Page url: http://www.gandalph3000.com/cast_xmr/linux/linux_version_of_cast-xmr-cryptonight-monero-miner-for-rx-vega-gpus/

It makes the software look a bit older than it is... :)

**Comment by makjaveli** [comment]
Thanks.

**Comment by glph3k** [comment]
Thanks. Fixed.
